package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"log"
	"matchme-server/database"
	"matchme-server/graph/model"
	"matchme-server/helpers"
	"matchme-server/middleware"
	"matchme-server/services"
	"time"

	pgx "github.com/jackc/pgx/v5"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, email string, password string) (*model.User, error) {
	if !helpers.IsValidEmail(email) {
		return nil, fmt.Errorf("email is invalid, please provide a valid email")
	}
	if !helpers.IsUniqEmail(email) {
		return nil, fmt.Errorf("email already exists")
	}
	if !helpers.IsValidPassword(password) {
		return nil, fmt.Errorf("password should be at least 6 symbols, one letter")
	}

	hashedPassword, err := helpers.HashPassword(password)
	if err != nil {
		log.Println(err)
		return nil, fmt.Errorf("internal server error (hashing)")
	}

	id, createdAt, err := database.CreateUser(ctx, r.DB, email, hashedPassword)
	if err != nil {
		log.Println(err)
		return nil, fmt.Errorf("internal server error (db)")
	}

	_, profilePicture := database.GetUserNamePhotoURL(ctx, r.DB, id)

	//    Note: gqlgen models are pointers
	return &model.User{
		UserID:         id,
		Email:          email,
		CreatedAt:      createdAt,
		ProfilePicture: &profilePicture,
	}, nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, email string, password string) (*model.LoginResponse, error) {
	userID, pwHash, err := database.GetUserByEmail(ctx, r.DB, email)

	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("user does not exist")
	}

	if err != nil {
		return nil, fmt.Errorf("internal server error (db)")
	}

	if !helpers.IsCorrectPassword(pwHash, password) {
		return nil, fmt.Errorf("invalid email or password")
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	access, err := helpers.MakeAccessToken(userID)
	if err != nil {
		return nil, fmt.Errorf("internal server error(access token)")
	}

	return &model.LoginResponse{
		Token: access,
		User:  user,
	}, nil
}

// DeletePhoto is the resolver for the deletePhoto field.
func (r *mutationResolver) DeletePhoto(ctx context.Context) (bool, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return false, gqlerror.Errorf("not authenticated")
	}

	if err := database.DeleteUserPhoto(ctx, r.DB, userID); err != nil {
		return false, gqlerror.Errorf("db error, failed to delete")
	}

	return true, nil
}

// UpsertReaction is the resolver for the upsertReaction field.
func (r *mutationResolver) UpsertReaction(ctx context.Context, targetedUserID string, reaction model.ReactionTypeEnum) (bool, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return false, gqlerror.Errorf("not authenticated")
	}

	if userID == targetedUserID {
		return false, gqlerror.Errorf("self reaction")
	}

	if reaction != "like" && reaction != "dislike" {
		return false, gqlerror.Errorf("reaction must be like or dislike")
	}

	if !helpers.IsValidID(targetedUserID) {
		return false, gqlerror.Errorf("user id is invalid")
	}

	err := database.UpsertReaction(ctx, r.DB, userID, targetedUserID, database.Reaction(reaction))
	if err != nil {
		return false, gqlerror.Errorf("db error")
	}

	if reaction == "like" {
		log.Printf("👍 User %s liked %s - creating connection request", userID, targetedUserID)

		connectionID, err := database.CreateConnectionRequest(ctx, r.DB, userID, targetedUserID)
		if err != nil {
			if err == database.ErrConnectionExists {
				log.Printf("Connection already exists between users")
				return false, gqlerror.Errorf("Connection already exists between users")
			} else {
				log.Printf("ERROR creating connection request: %v", err)
				return false, gqlerror.Errorf("db error")
			}
		} else {
			log.Printf("✅ Connection request created: %s (from %s to %s)", connectionID, userID, targetedUserID)
		}
	}

	return true, nil
}

// UpsertConnection is the resolver for the upsertConnection field.
func (r *mutationResolver) UpsertConnection(ctx context.Context, connectionID string, conType model.ConnectionTypeEnum) (bool, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return false, gqlerror.Errorf("not authenticated")
	}

	if conType != "accept" && conType != "reject" {
		return false, gqlerror.Errorf("connection type must be accept or reject")
	}

	if !helpers.IsValidID(connectionID) {
		return false, gqlerror.Errorf("connection id is invalid")
	}

	status := conType + "ed"

	err := database.UpdateConnectionStatus(ctx, r.DB, connectionID, userID, string(status))
	if err != nil {
		if err == database.ErrConnectionNotFound {
			return false, gqlerror.Errorf("connection request not found or already processed")
		}
		log.Printf("Error updating connection status: %v", err)
		return false, gqlerror.Errorf("db error")
	}

	log.Printf("✅ Connection %s %s by user %s", connectionID, status, userID)
	return true, nil
}

// DisconnectUsers is the resolver for the disconnectUsers field.
func (r *mutationResolver) DisconnectUsers(ctx context.Context, targetedUserID string) (bool, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return false, gqlerror.Errorf("not authenticated")
	}

	if userID == targetedUserID {
		return false, gqlerror.Errorf("self disconnect")
	}

	err := database.UpsertReaction(ctx, r.DB, userID, targetedUserID, database.ReactionDislike)
	if err != nil {
		return false, gqlerror.Errorf("db error")
	}

	err = database.DeleteConnectionAndChat(ctx, r.DB, userID, targetedUserID)
	if err != nil {
		return false, gqlerror.Errorf("db error")
	}

	return true, nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, chatID string, content string) (*model.Message, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("unauthorized")
	}

	sender, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	chat, _ := database.GetChatByID(ctx, r.DB, chatID, userID)
	if chat == nil {
		return nil, gqlerror.Errorf("chat not found with ID: %s", chatID)
	}

	// Now save the message
	messageId, err := database.SaveChatMessage(ctx, r.DB, chatID, userID, content)
	if err != nil {
		return nil, gqlerror.Errorf("failed to send message")
	}

	createdAt := time.Now()

	newMessage := &model.Message{
		ID:        messageId,
		Content:   content,
		CreatedAt: createdAt.Format(time.RFC3339),
		Sender:    sender, // Assign the sender you fetched
	}

	// Publish and return
	topic := fmt.Sprintf("chat:%s", chatID)
	GlobalPubSub.Publish(topic, newMessage)

	return newMessage, nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, name *string, about *string, languages []*string, addressCity *string, lat *float64, lon *float64, childName *string, childAbout *string, childInterests []*string) (*model.Profile, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("not authenticated")
	}

	// Convert []*string to []string for DB
	var langs []string
	for _, l := range languages {
		if l != nil {
			langs = append(langs, *l)
		}
	}

	var interests []string
	for _, i := range childInterests {
		if i != nil {
			interests = append(interests, *i)
		}
	}

	input := database.UpdateProfileInput{
		Name:           name,
		About:          about,
		AddressCity:    addressCity,
		Lat:            lat,
		Lon:            lon,
		ChildName:      childName,
		ChildAbout:     childAbout,
		Languages:      langs,
		ChildInterests: interests,
	}

	if err := database.UpdateProfile(ctx, r.DB, userID, input); err != nil {
		return nil, gqlerror.Errorf("failed to update profile: %v", err)
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	return profile, nil
}

// UpdateBio is the resolver for the updateBio field.
func (r *mutationResolver) UpdateBio(ctx context.Context, parentGender *model.GenderEnum, preferredDistance *int32, childBirthday *string, childGender *model.ChidGenderEnum, childActivityLevel *string, limitations []*string, allergies []*string, playStyles []*string) (*model.Bio, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("not authenticated")
	}

	// Convert []*string to []string for DB
	var limit []string
	for _, l := range limitations {
		if l != nil {
			limit = append(limit, *l)
		}
	}

	var allerg []string
	for _, i := range allergies {
		if i != nil {
			allerg = append(allerg, *i)
		}
	}

	var playst []string
	for _, i := range playStyles {
		if i != nil {
			playst = append(playst, *i)
		}
	}

	input := database.UpdateBioInput{
		ParentGender:       parentGender,
		PreferredDistance:  preferredDistance,
		ChildBirthday:      childBirthday,
		ChildGender:        childGender,
		ChildActivityLevel: childActivityLevel,
		Limitations:        limit,
		Allergies:          allerg,
		PlayStyles:         playst,
	}

	if err := database.UpdateBio(ctx, r.DB, userID, input); err != nil {
		return nil, gqlerror.Errorf("failed to update profile: %v", err)
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	return bio, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*model.User, error) {
	_, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user.Profile = profile
	user.Bio = bio

	return user, nil
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, userID string) (*model.Profile, error) {
	_, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		// User is not logged in.
		return nil, gqlerror.Errorf("Not authenticated")
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile.User = user

	return profile, nil
}

// Bio is the resolver for the bio field.
func (r *queryResolver) Bio(ctx context.Context, userID string) (*model.Bio, error) {
	_, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio.User = user

	return bio, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user.Profile = profile
	user.Bio = bio

	return user, nil
}

// MyBio is the resolver for the myBio field.
func (r *queryResolver) MyBio(ctx context.Context) (*model.Bio, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		return nil, gqlerror.Errorf("Not authenticated")
	}

	bio, err := r.GetBio(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	bio.User = user

	return bio, nil
}

// MyProfile is the resolver for the myProfile field.
func (r *queryResolver) MyProfile(ctx context.Context) (*model.Profile, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx) //just check that it is auth user
	if !ok {
		// User is not logged in.
		return nil, gqlerror.Errorf("Not authenticated")
	}

	profile, err := r.GetProfile(ctx, userID)
	if err != nil {
		return nil, err
	}

	user, err := r.GetUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	profile.User = user

	return profile, nil
}

// Recommendations is the resolver for the recommendations field.
func (r *queryResolver) Recommendations(ctx context.Context, limit *int32, offset *int32) ([]*model.User, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("unauthorized")
	}

	// 3. Profile Completion Check (Same as before)
	percent, err := database.GetProfileCompletionPercent(ctx, r.DB, userID)
	if err != nil {
		log.Println(err)
		return nil, gqlerror.Errorf("db error")
	}

	if percent < 100 {
		return nil, gqlerror.Errorf("Profile filled only %.1f%% — please complete your profile before viewing recommendations.", percent)
	}

	currentProfile, err := database.GetMatchingProfile(ctx, r.DB, userID)
	if err != nil || currentProfile == nil {
		log.Println(err)
		return nil, gqlerror.Errorf("db error")

	}

	currentPrefs, err := database.GetUserMatchingPreferences(ctx, r.DB, userID)
	if err != nil {
		log.Println(err)
		return nil, gqlerror.Errorf("db error")

	}

	candidates, err := database.GetPotentialMatches(ctx, r.DB, userID)
	if err != nil {
		log.Println(err)
		return nil, gqlerror.Errorf("db error")

	}
	matches := services.CalculateMatchingScores(currentProfile, currentPrefs, candidates, ctx)

	if len(matches) > 10 {
		matches = matches[:*limit]
	}

	var recommendations []string

	for _, match := range matches {
		recommendations = append(recommendations, string(match.UserID))
	}

	var users []*model.User

	for _, recommendedUserId := range recommendations {
		user, err := r.GetUser(ctx, recommendedUserId)
		if err != nil {
			return nil, err
		}

		profile, err := r.GetProfile(ctx, recommendedUserId)
		if err != nil {
			return nil, err
		}

		bio, err := r.GetBio(ctx, recommendedUserId)
		if err != nil {
			return nil, err
		}

		user.Profile = profile
		user.Bio = bio
		users = append(users, user)
	}

	return users, nil
}

// ConnectReguests is the resolver for the connectReguests field.
func (r *queryResolver) ConnectReguests(ctx context.Context, limit *int32, offset *int32) ([]*model.User, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("unauthorized")
	}

	// 3. Profile Completion Check (Same as before)
	percent, err := database.GetProfileCompletionPercent(ctx, r.DB, userID)
	if err != nil {
		log.Println(err)
		return nil, gqlerror.Errorf("db error")
	}

	if percent < 100 {
		return nil, gqlerror.Errorf("Profile is not complete")
	}

	// Get connection requests (with connection IDs)
	connectionRequests, err := database.GetIncomingConnectionRequests(ctx, r.DB, userID)
	if err != nil {
		return nil, gqlerror.Errorf("db error")
	}

	// Extract requester user IDs for response
	var users []*model.User

	for _, conn := range connectionRequests {
		user, err := r.GetUser(ctx, conn.RequesterUserID)
		if err != nil {
			return nil, err
		}

		profile, err := r.GetProfile(ctx, conn.RequesterUserID)
		if err != nil {
			return nil, err
		}

		bio, err := r.GetBio(ctx, conn.RequesterUserID)
		if err != nil {
			return nil, err
		}

		user.Profile = profile
		user.Bio = bio
		users = append(users, user)
	}

	return users, nil
}

// Connections is the resolver for the connections field.
func (r *queryResolver) Connections(ctx context.Context, limit *int32, offset *int32) ([]*model.User, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("unauthorized")
	}

	percent, err := database.GetProfileCompletionPercent(ctx, r.DB, userID)
	if err != nil {
		return nil, gqlerror.Errorf("db error")
	}

	if percent < 100 {
		return nil, gqlerror.Errorf("profile is not complete")
	}

	connections, err := database.GetConnections(ctx, r.DB, userID)
	if err != nil {
		return nil, gqlerror.Errorf("db error")
	}

	var users []*model.User

	for _, connectionUserID := range connections {
		user, err := r.GetUser(ctx, connectionUserID)
		if err != nil {
			return nil, err
		}

		profile, err := r.GetProfile(ctx, connectionUserID)
		if err != nil {
			return nil, err
		}

		bio, err := r.GetBio(ctx, connectionUserID)
		if err != nil {
			return nil, err
		}

		user.Profile = profile
		user.Bio = bio
		users = append(users, user)
	}

	return users, nil
}

// OnNewMessage is the resolver for the onNewMessage field.
func (r *subscriptionResolver) OnNewMessage(ctx context.Context, chatID string) (<-chan *model.Message, error) {
	userID, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, gqlerror.Errorf("unauthorized")
	}

	chat, err := database.GetChatByID(ctx, r.DB, chatID, userID)
	if err != nil || (chat.User1ID != userID && chat.User2ID != userID) {
		// If chat is nil or the user is not user1 or user2
		return nil, gqlerror.Errorf("access denied: you are not a member of this chat")
	}

	topic := fmt.Sprintf("chat:%s", chatID)

	msgChan, unsubscribe := GlobalPubSub.Subscribe(topic)
	go func() {
		<-ctx.Done()
		unsubscribe()
	}()

	return msgChan, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
